site_name: Lekkoatetyka - specyfika treningu biegacza średniodystansowego
theme:
  name: material
  palette:
    primary: deep orange
    accent: amber
extra_css:
  - stylesheets/custom.css
nav:
  - Strona Główna i Temat: index.md
  - Teoria Biegowa: teoria.md
  - Przykłady Treningów: przyklady.md
  - Autorzy i Organizacja: autorzy.md