site_name: Mini-kurs Podstawy Markdown i Git
theme:
  name: material
  palette:
    primary: indigo
    accent: light blue
extra_css:
  - stylesheets/custom.css
nav:
  - Strona Główna: index.md
  - Autorzy: autorzy.md
  - Teoria: teoria.md
  - Przykłady: przyklady.md